# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      run: ./gradlew build
    - name: Android test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        script: ./gradlew connectedAndroidTest
    - name: Coverage
      run: ./gradlew createDebugAndroidTestCoverageReport
