# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: nangua509/android:jdk8
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build inside container
      run: ./gradlew build
